---
kind: Service
apiVersion: v1
metadata:
  name: nodewebappservice
spec:
  type: LoadBalancer
  selector:
    app: nodewebapp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 9000

